amazonProperties:
  endpointUrl: https://s3.ap-northeast-10.amazonaws.com
  accessKey: AKIAQF2OAKBLARIPMDDD
  secretKey: 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
  UserName: user_app
  bucketName: genemes-pic
  region: ap-northeast-10
  localDir: upload-dir

slack_webhook: "https://hooks.slack.com/services/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"
github_token: "ghp_mQKNJGOlqeZnUk3555Zaqitjoeoeoeoeoeo"
